### ISSUE TITLE
Reading Git repository information should not be done on the EDT

### ISSUE THREAD

**Issue by lppedd** [JChrist/gitextender#13]
This happens in 2019.3 EAP invoking _Update All_.
It's not blocking.
```
java.lang.Throwable: Reading Git repository information should not be done on the EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at git4idea.repo.GitRepositoryImpl.update(GitRepositoryImpl.java:246)
	at com.intellij.dvcs.repo.AbstractRepositoryManager.lambda$updateAllRepositories$0(AbstractRepositoryManager.java:108)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:962)
	at com.intellij.dvcs.repo.AbstractRepositoryManager.updateAllRepositories(AbstractRepositoryManager.java:107)
	at gr.jchrist.gitextender.GitExtenderUpdateAll.actionPerformed(GitExtenderUpdateAll.java:51)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:508)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:828)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by JChrist** [comment]
Hi! Thanks for this report! I will try reproducing it using the latest eap snapshot and possibly come up with an update. Hopefully before the EAP gets released! 😅

**Comment by lppedd** [comment]
@JChrist hi! Thank you!

**Comment by JChrist** [comment]
:)
I uploaded the new version, so clicking on Help->Check for Updates should bring it up.

**Comment by lppedd** [comment]
@JChrist confirm it's fixed. However we lost the loading indicator (spinner).
