### ISSUE TITLE
Fatal errors in the IDE

### ISSUE THREAD

**Issue by nprasath002** [JChrist/gitextender#2]
PHPstorm version - 9.0

Today i installed Gitextender in PHPstorm and got the following errors

`cannot create class "gr.jchrist.gitextender.GitExtenderUpdateAll" [Plugin: gr.jchrist.gitextender]
com.intellij.diagnostic.PluginException: cannot create class "gr.jchrist.gitextender.GitExtenderUpdateAll" [Plugin: gr.jchrist.gitextender]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:516)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:496)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:489)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1310)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1303)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1303)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1318)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1318)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:1318)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1297)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.c(ActionManagerImpl.java:1288)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:76)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1268)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.intellij.diagnostic.PluginException: gr/jchrist/gitextender/GitExtenderUpdateAll : Unsupported major.minor version 51.0 [Plugin: gr.jchrist.gitextender]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
	... 24 more
Caused by: java.lang.UnsupportedClassVersionError: gr/jchrist/gitextender/GitExtenderUpdateAll : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 30 more
`

Let me know if you need more info

Thanks

**Comment by JChrist** [comment]
It seems that it is a problem with the Java version you use to run the IDE. Are you using Java 7+?

**Comment by nprasath002** [comment]
I am using Java 8 Update 51 on a Mac OS 10.10.4

**Comment by JChrist** [comment]
The error seems to be that the JRE running the IDE cannot support a java 7 class: Unsupported major.minor version 51.0 (51.0 is java 7).
Can you please check again to make sure that your IDE is running in java 7 or java 8, e.g. by running: ps aux | grep java and find the running IDE instance?

**Comment by nprasath002** [comment]
Your right. My IDE is running JDK 1.6+

**Comment by JChrist** [comment]
While I'm considering making the plugin compatible with java 6, for now you will have to start the IDE with java 7+
