### ISSUE TITLE
Error Updating All 

### ISSUE THREAD

**Issue by mxkyu** [JChrist/gitextender#21]
There is an error during update all repos. 

**Git Extender update failed:**
`Git repo: project Error: Git Extender failed to update git repo, due to an exception during update. The exception was: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@238dfaa1 Current thread: Thread[Thread-15,6,Idea Thread Group] 631590894 SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1427407249`

Version: _PhpStorm 2020.3.2_

It updates 1 repo but failed update on another repo after switch to this repo. I must do multiple ALT+T to update all branches with that error. This error shows then you add a option (GitExtender -> UpdateAll) in main "Git" menu.

**Comment by mxkyu** [comment]
I hope you find a time to fix this. Thank you.

**Comment by JChrist** [comment]
Hi @mxkyu, thanks for reporthing this. My main issue (apart from the time) is that I have no idea what causes the error and what to do about it :(

**Comment by mxkyu** [comment]
OK, how can i help you find a clue to solve this problem?

Logs (anonymize): 

> 2021-03-27 21:04:47,349 [133056065]   INFO -  #git4idea.commands.GitHandler - [my-project] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune 
2021-03-27 21:04:48,299 [133057015]   INFO -  #git4idea.commands.GitHandler - warning: redirecting to http://repo/my-project.git/ 
2021-03-27 21:04:48,413 [133057129]   INFO -  #git4idea.commands.GitHandler - [my-project] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false checkout feature/test-branch-update 
2021-03-27 21:04:48,548 [133057264]   INFO -  #git4idea.commands.GitHandler - Already on 'feature/test-branch-update' 
2021-03-27 21:04:48,606 [133057322]   INFO -  #git4idea.commands.GitHandler - [my-project] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false merge --ff-only origin/feature/test-branch-update 
2021-03-27 21:04:48,923 [133057639]   WARN - .gitextender.RepositoryUpdater - exception trying to update repo: C:\Users\user\my-project from thread:Thread-80 
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@7bfe926d
Current thread: Thread[Thread-80,6,Idea Thread Group] 1545429274
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 634945154
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1088)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1063)
	at com.intellij.openapi.vcs.changes.ui.ChangesTree.updateTreeModel(ChangesTree.java:362)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserBase$ChangesBrowserTreeList.rebuildTree(ChangesBrowserBase.java:301)
	at com.intellij.openapi.vcs.changes.ui.SimpleChangesBrowser.setChangesToDisplay(SimpleChangesBrowser.java:42)
	at com.intellij.openapi.vcs.changes.committed.CommittedChangesTreeBrowser.updateBySelectionChange(CommittedChangesTreeBrowser.java:268)
	at com.intellij.openapi.vcs.changes.committed.CommittedChangesTreeBrowser.<init>(CommittedChangesTreeBrowser.java:131)
	at com.intellij.openapi.vcs.update.UpdateInfoTree.createCenterPanel(UpdateInfoTree.java:147)
	at com.intellij.openapi.ui.PanelWithActionsAndCloseButton.init(PanelWithActionsAndCloseButton.java:63)
	at com.intellij.openapi.vcs.update.UpdateInfoTree.<init>(UpdateInfoTree.java:109)
	at gr.jchrist.gitextender.handlers.AfterSuccessfulMergeHandler.generateUpdateInfoTree(AfterSuccessfulMergeHandler.java:98)
	at gr.jchrist.gitextender.handlers.AfterSuccessfulMergeHandler.showUpdatedFiles(AfterSuccessfulMergeHandler.java:66)
	at gr.jchrist.gitextender.handlers.AfterSuccessfulMergeHandler.afterMerge(AfterSuccessfulMergeHandler.java:36)
	at gr.jchrist.gitextender.BranchUpdater.afterMerge(BranchUpdater.java:99)
	at gr.jchrist.gitextender.BranchUpdater.merge(BranchUpdater.java:75)
	at gr.jchrist.gitextender.BranchUpdater.update(BranchUpdater.java:48)
	at gr.jchrist.gitextender.RepositoryUpdater.updateRepository(RepositoryUpdater.java:135)
	at gr.jchrist.gitextender.BackgroundableRepoUpdateTask.run(BackgroundableRepoUpdateTask.java:36)
	at java.base/java.lang.Thread.run(Thread.java:834)

When i try paste last git command: "git -c credential.helper= -c core.quotepath=false -c log.showSignature=false merge --ff-only origin/feature/test-branch-update" everything is OK. So, its not a git command provoke an error but some thing else...

**Comment by gsaslis** [comment]
@JChrist I am also regularly hitting this issue as of recently (unfortunately I don't have any exact dates to offer...). It looks like it is caused by some change in a new intellij version ?

In an intellij project where I have lots of git repos checked out and updating them at once it happens pretty consistently (almost every time).  I am happy to have a debugging session together, if that helps, or share any other logs, etc. if you can point me to what you'd need. 

[This issue](https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2304) also looks related, so perhaps some hint lies within [the fix they applied](https://github.com/GoogleCloudPlatform/cloud-code-intellij/pull/2307)? I know it's from a while back, but that was the best I could find... 

A similar issue is also reported in: https://www.programmersought.com/article/82805792212/

**Comment by JChrist** [comment]
Amazing report @gsaslis! Thanks! 
Now if only I could find the time to check this through...
Unfortunately, I can't make any promises.

**Comment by JChrist** [comment]
It all seems to stem from the messy attempt to generate the `UpdateInfoTree` and show it (in the git changes tab).
One quick hacky way to avoid this would be disabling this call: https://github.com/JChrist/gitextender/blob/89685d982d6c21d4f63c26dac9b0e17912e73167/src/main/java/gr/jchrist/gitextender/handlers/AfterSuccessfulMergeHandler.java#L36
Can you try it?

**Comment by gsaslis** [comment]
@JChrist nice, thanks for taking a look!! 

How could I go about building / installing the locally built version into my intellij instance? I'd be happy to give that a try if there are any docs you can point me to ?

**Comment by JChrist** [comment]
Really tough one... Documentation is lacking.
Basically, the build uses the [Intellij Gradle Plugin](https://github.com/JetBrains/gradle-intellij-plugin).
The gradle build contains some tasks that should help.
One is the `runIde` task, which fires up a community Intellij instance with the plugin installed.
The other one is the `buildPlugin`, which creates (and buries somewhere) the plugin, ready to be manually installed on an Intellij instance.

**Comment by oviron** [comment]
@JChrist Hey, i tried to build a plugin with `showUpdatedFiles();` commented out and it works just fine.

BTW, for everyoune who wants to try it themselves, `buildPlugin` buries the plugin in `build/distributions` :)

**Comment by JChrist** [comment]
awesome @oviron, I'm going to create a new release then with `showUpdatedFiles` left out.
If/When I find some time, I may have a better look at it in the future.

**Comment by gsaslis** [comment]
@JChrist happy customer here!! 👋 

this has fixed that annoying issue! 🎉
