### ISSUE TITLE
Exception when runing (when there are 2 projects opening)

### ISSUE THREAD

**Issue by hoangtranwork** [JChrist/gitextender#9]
I was just running this tool normally (mac os, latest IntelliJ 2017.3)

The 2 screenshot of the error popup:
https://www.dropbox.com/s/uqk9bomn6b5vszu/Screenshot%202017-12-06%2015.41.13.png?dl=0
https://www.dropbox.com/s/ilbonwhqf8l6sd4/Screenshot%202017-12-06%2015.42.11.png?dl=0

Stacktrace:
```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@634bddbb Current thread: Thread[ApplicationImpl pooled thread 31,4,Idea Thread Group] 174860262 SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 267529812

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:486)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1089)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1078)
	at com.intellij.openapi.vcs.changes.ui.ChangesTree.updateTreeModel(ChangesTree.java:250)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserBase$MyChangesTreeList.rebuildTree(ChangesBrowserBase.java:234)
	at com.intellij.openapi.vcs.changes.ui.SimpleChangesBrowser.setChangesToDisplay(SimpleChangesBrowser.java:56)
	at com.intellij.openapi.vcs.changes.committed.CommittedChangesTreeBrowser.f(CommittedChangesTreeBrowser.java:282)
	at com.intellij.openapi.vcs.changes.committed.CommittedChangesTreeBrowser.<init>(CommittedChangesTreeBrowser.java:147)
	at com.intellij.openapi.vcs.update.UpdateInfoTree.createCenterPanel(UpdateInfoTree.java:161)
	at com.intellij.openapi.ui.PanelWithActionsAndCloseButton.init(PanelWithActionsAndCloseButton.java:76)
	at com.intellij.openapi.vcs.update.UpdateInfoTree.<init>(UpdateInfoTree.java:122)
	at gr.jchrist.gitextender.handlers.AfterSuccessfulMergeHandler.generateUpdateInfoTree(AfterSuccessfulMergeHandler.java:100)
	at gr.jchrist.gitextender.handlers.AfterSuccessfulMergeHandler.showUpdatedFiles(AfterSuccessfulMergeHandler.java:67)
	at gr.jchrist.gitextender.handlers.AfterSuccessfulMergeHandler.afterMerge(AfterSuccessfulMergeHandler.java:36)
	at gr.jchrist.gitextender.BranchUpdater.afterMerge(BranchUpdater.java:100)
	at gr.jchrist.gitextender.BranchUpdater.merge(BranchUpdater.java:75)
	at gr.jchrist.gitextender.BranchUpdater.update(BranchUpdater.java:48)
	at gr.jchrist.gitextender.RepositoryUpdater.updateRepository(RepositoryUpdater.java:114)
	at gr.jchrist.gitextender.BackgroundableRepoUpdateTask.run(BackgroundableRepoUpdateTask.java:38)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:704)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hoangtranwork** [comment]
[threadDump.txt](https://github.com/JChrist/gitextender/files/1534423/threadDump.txt)

**Comment by JChrist** [comment]
Hi @hoangtranwork !
Thanks for the bug report!
I am aware of this issue (experienced it myself as well).
It has been reported in #8 , so I will mark this as duplicate.
As far as I can tell right now, this seems to only impact the displayed results of updated files, the branches are still correctly getting updated.
I am planning on resolving this issue as soon as I find some time.

**Comment by hoangtranwork** [comment]
Thank you @JChrist, sorry for not searching the issue list first. And it's kind of inconvenient when IDEA doesn't allow us to send the issue directly from that error popup.
